/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        archivo: ['Archivo', 'sans-serif'],
        helvetica: ['Helvetica', 'sans-serif'],
        varela: ['Varela Round', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['96px', '104px'],
        h2: ['72px', '72px'],
        h3: ['60px', '60px'],
        h4: ['48px', '48px'],
        h5: ['36px', '39px'],
        h6: ['24px', '26px'],
        'sub-1': ['32px', '39px'],
        'sub-2': ['24px', '29px'],
        'sub-3': ['20px', '24px'],
        'body-1': ['16px', '18px'],
        'body-2': ['14x', '16px'],
        'body-3': ['12px', '14px'],
      },
      colors: {
        'arkav-yellow-light': '#ffd271',
        'arkav-yellow': '#feb20e',
        'arkav-yellow-dark': '#df9800',
        'arkav-red-light': '#ff634b',
        'arkav-red': '#f43518',
        'arkav-red-dark': '#b71800',
        'arkav-green-light': '#e6feed',
        'arkav-green': '#069154',
        'arkav-green-dark': '#01703f',
        'arkav-blue-light': '#6979be',
        'arkav-blue': '#1f307c',
        'arkav-blue-dark': '#0b1a5c',
        'arkav-cream-light': '#fff2eb',
        'arkav-cream': '#ffeadf',
        'arkav-cream-dark': '#f5d5c4',
        'arkav-pink-light': '#fee9e6',
        'arkav-pink': '#e28281',
        'arkav-pink-dark': '#c86564',
        'arkav-grey-200': '#f9f9f9',
        'arkav-grey-300': '#c4c4c4',
        'arkav-grey-400': '#9b9b9b',
        'arkav-grey-500': '#777676',
        'arkav-grey-600': '#535252',
        'arkav-grey-700': '#2f2e2e',
        'arkav-black': '#0b0a0a',
      },
      backgroundImage: {
        home_bg: "url('../public/img/homepage-bg.svg')",
      },
    },
  },
  plugins: [],
};
